FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir --retries 10 --timeout 120 -r requirements.txt
COPY main.py .
COPY db.py .
COPY auth.py .
COPY worker.py .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]