import { useEffect, useState } from "react";
import LegalLayout from "../components/LegalLayout";
import { api } from "../api";

export default function PrivacyPolicy() {
  const [meta, setMeta] = useState(null);

  useEffect(() => {
    api.getLegalMeta().then(setMeta).catch(() => {});
    api.logLegalView("privacy").catch(() => {});
  }, []);

  const c = meta?.contact;
  const email = c?.email || "akinfeadesanmit@gmail.com";
  const name = c?.name || "Akinfe Adesanmi";
  const phone = c?.phone || "08120697429";
  const website = c?.website || "https://www.hygini.app";

  return (
    <LegalLayout
      title="Privacy Policy"
      updated={meta?.privacy?.updated_at || "September 5, 2026"}
      effective={meta?.privacy?.effective_at || "September 5, 2026"}
      otherDocHref="/terms"
      otherDocLabel="View Terms of Use"
    >
      <p>
        This Privacy Policy explains how OSF-Suite (&ldquo;OSF-Suite,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or
        &ldquo;our&rdquo;), accessible at www.hygini.app, collects, uses, discloses, and protects information when
        you use our website and our AI-powered sales coaching and revenue intelligence platform (the
        &ldquo;Service&rdquo;).
      </p>

      <div className="osf-legal-notice">
        <strong>Note:</strong> Because OSF-Suite processes call recordings — which carry stricter legal
        requirements than ordinary SaaS data — please have this reviewed by counsel in your jurisdiction before
        relying on it as your final policy.
      </div>

      <h2>1. Who this policy covers</h2>
      <p>OSF-Suite is used by two kinds of people, and this policy applies to both:</p>
      <ul>
        <li>
          <strong>Customers and Users</strong> — the sales organizations, managers, and reps who sign up for an
          OSF-Suite account, upload pricing or product materials, and use the platform to record and analyze
          their calls.
        </li>
        <li>
          <strong>Call Participants</strong> — the other party on a sales call (prospects, clients) who did not
          sign up for OSF-Suite but whose voice, words, and business information are captured because a User
          recorded a call with them.
        </li>
      </ul>
      <p>
        If you are a Call Participant and want to understand your rights or request that your data be deleted,
        see Section 9.
      </p>

      <h2>2. Information we collect</h2>
      <h3>2.1 Information you provide directly</h3>
      <ul>
        <li>Account information: name, work email, phone number, company name, role</li>
        <li>Billing information: processed by our payment processor (we do not store full card numbers)</li>
        <li>
          Company context: pricing sheets, pitch decks, product docs, and other materials you upload so
          OSF-Suite can ground coaching against your own materials
        </li>
        <li>Support communications: anything you send us via email or in-app chat</li>
      </ul>

      <h3>2.2 Information collected from calls</h3>
      <p>This is the core of what OSF-Suite processes, and the most sensitive category we handle:</p>
      <ul>
        <li><strong>Audio and/or video</strong> of sales calls you choose to record or upload</li>
        <li><strong>Transcripts</strong> generated from that audio, including speaker-separated dialogue</li>
        <li>
          <strong>Metadata:</strong> call date/time, duration, participants, and the CRM/deal record the call is
          linked to (if connected)
        </li>
        <li>
          <strong>Derived data:</strong> objection tags, buying-signal flags, talk-ratio metrics, deal health
          scores, and coaching notes generated by our AI from the above
        </li>
      </ul>

      <h3>2.3 Information collected automatically</h3>
      <ul>
        <li>
          Device and usage data (browser type, IP address, pages visited, session length) via standard analytics
        </li>
        <li>Cookies and similar technologies for login sessions and product analytics (see Section 8)</li>
      </ul>

      <h2>3. How we use information</h2>
      <p>We use the information above to:</p>
      <ul>
        <li>Provide the core Service: transcribe calls, generate live nudges, and produce post-call coaching reports</li>
        <li>Personalize coaching against your uploaded pricing, positioning, and product materials</li>
        <li>Generate team-level analytics for managers (deal health, coaching plans, top-performer libraries)</li>
        <li>
          Maintain, secure, and improve the Service, including evaluating our own product features (see Section
          4 for limits on AI model training)
        </li>
        <li>Communicate with you about your account, billing, and product updates</li>
        <li>Comply with legal obligations and enforce our Terms of Use</li>
      </ul>
      <p>
        <strong>We do not sell personal information.</strong> We do not use your call recordings or transcripts
        to build a shared dataset used to coach or benefit other customers — your data trains and informs
        coaching for your account only, unless you opt in otherwise.
      </p>

      <h2>4. AI processing and third-party subprocessors</h2>
      <p>
        OSF-Suite uses third-party AI/large language model providers to power transcription, live nudges, and
        coaching analysis. This means call audio and transcript text is transmitted to and processed by these
        providers on our behalf, under contractual terms that restrict them from using your data to train their
        own general-purpose models unless you separately opt in.
      </p>
      <ul>
        <li>We select subprocessors that offer encryption in transit and at rest, and contractual data-use restrictions.</li>
        <li>
          We maintain (and will publish, or provide on request) a current list of AI and infrastructure
          subprocessors used to deliver the Service.
        </li>
        <li>
          If we change or add a subprocessor in a way that materially changes how your data is handled, we will
          notify account administrators in advance where required by law.
        </li>
        <li>
          Where required (e.g., under GDPR or the NDPA for cross-border transfers), we rely on appropriate
          safeguards such as standard contractual clauses with these providers.
        </li>
      </ul>
      <p>
        If you require a specific subprocessor list or a Data Processing Addendum (DPA) for your organization&rsquo;s
        compliance needs, contact us at the address in Section 12.
      </p>

      <h2>5. Call recording consent — your responsibility as a User</h2>
      <p>
        <strong>This is important, and it is on you, not us.</strong> Recording a phone or video call without
        proper notice or consent is illegal in many jurisdictions — including &ldquo;two-party consent&rdquo;
        states in the US and equivalent rules under Nigerian, EU, and UK law.
      </p>
      <p>By using OSF-Suite to record a call, you (the User/Customer) represent and warrant that:</p>
      <ol>
        <li>
          You have obtained all consents required under the laws applicable to you and the other call
          participant(s) before recording.
        </li>
        <li>
          You will provide clear notice (verbally, via a consent banner, or in your meeting invite) that the
          call is being recorded and analyzed by AI.
        </li>
        <li>
          You are solely responsible for your organization&rsquo;s compliance with applicable call-recording,
          wiretap, and data protection laws. OSF-Suite provides the tooling; it does not provide legal advice on
          when or how you may lawfully record.
        </li>
      </ol>
      <p>
        OSF-Suite is not liable for a User&rsquo;s failure to obtain required consent from call participants.
      </p>

      <h2>6. How long we keep information</h2>
      <ul>
        <li>
          <strong>Call recordings and transcripts</strong> are retained for as long as your account is active,
          or until you delete them, whichever comes first. You can delete individual calls or your full call
          history from your dashboard at any time.
        </li>
        <li>
          <strong>Account and billing data</strong> is retained for the duration of your account plus the period
          required for tax, accounting, and legal record-keeping (typically up to 7 years).
        </li>
        <li>
          <strong>Data after cancellation:</strong> when you cancel, we retain your data for 30 days (in case you
          want to reactivate or export it), after which it is deleted from active systems, subject to backups
          that are purged on a rolling schedule.
        </li>
      </ul>

      <h2>7. How we share information</h2>
      <p>We share information only in these circumstances:</p>
      <ul>
        <li><strong>AI and infrastructure subprocessors</strong> (Section 4), to deliver the Service</li>
        <li><strong>Payment processors</strong>, to bill you</li>
        <li>
          <strong>Within your organization:</strong> recordings, transcripts, and coaching reports linked to your
          company&rsquo;s account are visible to the managers/admins your organization has granted access to
        </li>
        <li>
          <strong>Legal reasons:</strong> if required by law, subpoena, or to protect the rights, safety, or
          property of OSF-Suite, our users, or the public
        </li>
        <li>
          <strong>Business transfers:</strong> if OSF-Suite is acquired or merges with another company, your
          information may transfer as part of that transaction, subject to this policy or a comparable one
        </li>
      </ul>
      <p>We do not share call recordings, transcripts, or derived coaching data with other OSF-Suite customers.</p>

      <h2>8. Cookies and analytics</h2>
      <p>
        We use cookies and similar tools to keep you logged in, remember preferences, and understand product
        usage (e.g., which features are used most). You can control cookies through your browser settings;
        disabling some cookies may affect core functionality like staying logged in.
      </p>

      <h2>9. Your rights</h2>
      <p>
        Depending on your location, you may have rights to access, correct, export, or delete your personal
        data, and to object to or restrict certain processing. This applies under:
      </p>
      <ul>
        <li>The <strong>Nigeria Data Protection Act, 2023 (NDPA)</strong>, for individuals in Nigeria</li>
        <li>The <strong>GDPR/UK GDPR</strong>, for individuals in the EU/UK</li>
        <li><strong>US state privacy laws</strong> (e.g., CCPA/CPRA), for applicable US residents</li>
      </ul>
      <p>
        <strong>Call Participants:</strong> if you were on a call recorded through OSF-Suite and are not the
        account holder, you can request access to or deletion of your data by contacting the sales organization
        that recorded the call directly (they control the recording), or by emailing us at the address below and
        we will route your request to the relevant Customer.
      </p>
      <p>
        To exercise any of these rights, email <a href={`mailto:${email}`}>{email}</a> with
        the subject line &ldquo;Privacy Request.&rdquo; We will respond within the timeframe required by
        applicable law (generally 30 days).
      </p>

      <h2>10. Security</h2>
      <p>
        We use industry-standard safeguards — encryption in transit and at rest, access controls, and
        least-privilege permissions — to protect your data. No system is 100% secure, and we cannot guarantee
        absolute security, but we will notify affected users and, where required, the Nigeria Data Protection
        Commission (NDPC) or other relevant authority, within legally mandated timeframes in the event of a
        breach affecting personal data.
      </p>

      <h2>11. International data transfers</h2>
      <p>
        OSF-Suite and its subprocessors may process data outside Nigeria, including in the United States or the
        EU. Where we transfer personal data of Nigerian, EU, or UK individuals across borders, we rely on
        recognized safeguards such as standard contractual clauses or equivalent mechanisms recognized under the
        NDPA and GDPR.
      </p>

      <h2>12. Contact us</h2>
      <p>
        <strong>OSF-Suite</strong>
        <br />
        {name}
        <br />
        Email: <a href={`mailto:${email}`}>{email}</a>
        <br />
        Phone: {phone}
        <br />
        Website: <a href={website}>{website.replace("https://", "")}</a>
      </p>

      <h2>13. Changes to this policy</h2>
      <p>
        We may update this Privacy Policy from time to time. If changes are material, we will notify account
        administrators by email or in-app notice before the change takes effect. Continued use of the Service
        after changes take effect constitutes acceptance.
      </p>
    </LegalLayout>
  );
}