import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { createRouter, RouterProvider } from '@tanstack/react-router'

// Generated by @tanstack/router-plugin from everything in src/routes/ —
// this file does not exist until `npm run dev` or `npm run build` has
// run at least once. If your editor shows this import as missing,
// that's expected before the first build.
import { routeTree } from './routeTree.gen'

const router = createRouter({ routeTree })

// Ambient module augmentation would normally go in a .d.ts file, but
// since this project is plain JS, TanStack's router still works fine
// without it — this comment is just documenting that we're skipping
// the optional TypeScript route-typing step, not that anything is broken.

const rootEl = document.getElementById('root')

createRoot(rootEl).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>
)
